if(NOT DEFINED FONTCOLLECTOR_EXE)
	message(FATAL_ERROR "FONTCOLLECTOR_EXE is required")
endif()

if(NOT DEFINED TEST_WORK_DIR)
	set(TEST_WORK_DIR "${CMAKE_CURRENT_BINARY_DIR}/fontcollector-cli-smoke")
endif()

file(REMOVE_RECURSE "${TEST_WORK_DIR}")
file(MAKE_DIRECTORY "${TEST_WORK_DIR}")

set(COMMON_HEADER "[Script Info]\nScriptType: v4.00+\nWrapStyle: 0\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")

set(A_ASS "${TEST_WORK_DIR}/a.ass")
set(B_ASS "${TEST_WORK_DIR}/b.ass")
set(MISSING_ASS "${TEST_WORK_DIR}/missing.ass")
set(SIMHEI_ASS "${TEST_WORK_DIR}/simhei.ass")
set(SIMHEI_LOCALIZED_ASS "${TEST_WORK_DIR}/simhei-localized.ass")
set(NESTED_TRANSFORM_ASS "${TEST_WORK_DIR}/nested-transform.ass")
set(TAB_ASS "${TEST_WORK_DIR}/tab.ass")
set(SPACES_ASS "${TEST_WORK_DIR}/spaces.ass")
set(WRAP_RESET_ASS "${TEST_WORK_DIR}/wrap-reset.ass")
set(ESCAPED_BRACES_ASS "${TEST_WORK_DIR}/escaped-braces.ass")
set(DRAWING_ASS "${TEST_WORK_DIR}/drawing.ass")
set(NESTED_DRAWING_ASS "${TEST_WORK_DIR}/nested-drawing.ass")
set(NESTED_TEXT_ASS "${TEST_WORK_DIR}/nested-text.ass")
set(VARIANT_STATE_ASS "${TEST_WORK_DIR}/variant-state.ass")
set(COPY_DIR "${TEST_WORK_DIR}/copy")

file(WRITE "${A_ASS}" "${COMMON_HEADER}Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,ASCII only\n")
file(WRITE "${B_ASS}" "${COMMON_HEADER}; physical line padding\nDialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,Missing maybe 一\n")
file(WRITE "${MISSING_ASS}" "[Script Info]\nScriptType: v4.00+\nWrapStyle: 0\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,DefinitelyMissingAegisubFont,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n; padding\nDialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,Hello\n")
file(WRITE "${SIMHEI_ASS}" "[Script Info]\nScriptType: v4.00+\nWrapStyle: 0\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,SimHei,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\nDialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,Hello\n")
file(WRITE "${SIMHEI_LOCALIZED_ASS}" "[Script Info]\nScriptType: v4.00+\nWrapStyle: 0\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,黑体,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\nDialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\\fn黑体}Hello\n")
file(WRITE "${NESTED_TRANSFORM_ASS}" "${COMMON_HEADER}Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\\t(0,1000,\\fnDefinitelyMissingNestedFont)}X\n")
file(WRITE "${TAB_ASS}" "${COMMON_HEADER}Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,A\tB\n")
file(WRITE "${SPACES_ASS}" "${COMMON_HEADER}Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,A\\hB C\n")
file(WRITE "${WRAP_RESET_ASS}" "${COMMON_HEADER}Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\\q2}A{\\q}B\\nC\n")
file(WRITE "${ESCAPED_BRACES_ASS}" "${COMMON_HEADER}Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,A\\{B\\}C\n")
file(WRITE "${DRAWING_ASS}" "${COMMON_HEADER}Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\\p1}m 0 0 l 10 0 10 10 0 10{\\p0}\n")
file(WRITE "${NESTED_DRAWING_ASS}" "${COMMON_HEADER}Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\\t(0,1000,\\p1)}m 0 0 l 10 0 10 10 0 10\n")
file(WRITE "${NESTED_TEXT_ASS}" "${COMMON_HEADER}Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\\p1\\t(0,1000,\\p0)}A\n")
file(WRITE "${VARIANT_STATE_ASS}" "${COMMON_HEADER}Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\\b600\\fe-1}A\n")

function(run_fontcollector EXPECTED_RESULT)
	execute_process(
		COMMAND "${FONTCOLLECTOR_EXE}" ${ARGN}
		RESULT_VARIABLE actual_result
		OUTPUT_VARIABLE output
		ERROR_VARIABLE error
	)
	if(NOT actual_result EQUAL EXPECTED_RESULT)
		message(FATAL_ERROR "fontcollector ${ARGN} returned ${actual_result}, expected ${EXPECTED_RESULT}\nstdout:\n${output}\nstderr:\n${error}")
	endif()
	set(FONTCOLLECTOR_STDOUT "${output}" PARENT_SCOPE)
	set(FONTCOLLECTOR_STDERR "${error}" PARENT_SCOPE)
endfunction()

function(require_contains TEXT NEEDLE LABEL)
	string(FIND "${TEXT}" "${NEEDLE}" found_at)
	if(found_at LESS 0)
		message(FATAL_ERROR "missing ${LABEL}: ${NEEDLE}\ntext:\n${TEXT}")
	endif()
endfunction()

function(require_not_contains TEXT NEEDLE LABEL)
	string(FIND "${TEXT}" "${NEEDLE}" found_at)
	if(NOT found_at LESS 0)
		message(FATAL_ERROR "unexpected ${LABEL}: ${NEEDLE}\ntext:\n${TEXT}")
	endif()
endfunction()

function(json_get OUT JSON_TEXT)
	string(JSON value ERROR_VARIABLE json_error GET "${JSON_TEXT}" ${ARGN})
	if(json_error)
		message(FATAL_ERROR "json get failed at ${ARGN}: ${json_error}\njson:\n${JSON_TEXT}")
	endif()
	set(${OUT} "${value}" PARENT_SCOPE)
endfunction()

function(json_length OUT JSON_TEXT)
	string(JSON value ERROR_VARIABLE json_error LENGTH "${JSON_TEXT}" ${ARGN})
	if(json_error)
		message(FATAL_ERROR "json length failed at ${ARGN}: ${json_error}\njson:\n${JSON_TEXT}")
	endif()
	set(${OUT} "${value}" PARENT_SCOPE)
endfunction()

function(require_json_equals JSON_TEXT EXPECTED LABEL)
	json_get(actual "${JSON_TEXT}" ${ARGN})
	if(NOT actual STREQUAL EXPECTED)
		message(FATAL_ERROR "json ${LABEL} was ${actual}, expected ${EXPECTED}\njson:\n${JSON_TEXT}")
	endif()
endfunction()

function(require_json_array_contains JSON_TEXT EXPECTED LABEL)
	set(path ${ARGN})
	json_length(item_count "${JSON_TEXT}" ${path})
	foreach(i RANGE 0 ${item_count})
		if(i EQUAL item_count)
			break()
		endif()
		json_get(actual "${JSON_TEXT}" ${path} ${i})
		if(actual STREQUAL EXPECTED)
			return()
		endif()
	endforeach()
	message(FATAL_ERROR "json ${LABEL} did not contain ${EXPECTED}\njson:\n${JSON_TEXT}")
endfunction()

file(READ "${MISSING_ASS}" MISSING_ASS_BEFORE_NORMALIZE)
run_fontcollector(0 normalize "${MISSING_ASS}" --target english --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "2" "normalize schema version" schema_version)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "normalize" "normalize command" command)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "english" "normalize target" target)
# CMake string(JSON GET) reports JSON true as ON.
require_json_equals("${FONTCOLLECTOR_STDOUT}" "ON" "normalize root catalog available" summary catalog_available)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "ON" "normalize file catalog available" files 0 summary catalog_available)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "1" "normalize unsafe finding count" summary unsafe_finding_count)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "unrecognized_family_name" "normalize reason" files 0 changes 0 reason)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "style" "normalize source kind" files 0 changes 0 source kind)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "Default" "normalize source style" files 0 changes 0 source style)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "7" "normalize style source line" files 0 changes 0 source line)
file(READ "${MISSING_ASS}" MISSING_ASS_AFTER_NORMALIZE)
if(NOT MISSING_ASS_BEFORE_NORMALIZE STREQUAL MISSING_ASS_AFTER_NORMALIZE)
	message(FATAL_ERROR "normalize command modified its input file")
endif()

run_fontcollector(0 normalize "${MISSING_ASS}" --target localized --details)
require_contains("${FONTCOLLECTOR_STDOUT}" "ISSUE: style 'Default' (line 7)" "normalize human style line")
require_contains("${FONTCOLLECTOR_STDOUT}" "unrecognized_family_name" "normalize human reason")

run_fontcollector(0 check "${A_ASS}" "${B_ASS}" --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "2" "json schema version" schema_version)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "platform" "default matcher root" matcher)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "platform" "default matcher file" files 0 matcher)
json_length(file_count "${FONTCOLLECTOR_STDOUT}" files)
if(NOT file_count EQUAL 2)
	message(FATAL_ERROR "expected two file reports, got ${file_count}\njson:\n${FONTCOLLECTOR_STDOUT}")
endif()
require_json_equals("${FONTCOLLECTOR_STDOUT}" "0" "clean file glyph summary" files 0 summary missing_glyph_font_count)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "1" "glyph-missing file summary" files 1 summary missing_glyph_font_count)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "11" "first file source line" files 0 font_usage 0 lines 0)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "missing_glyphs" "missing glyph diagnostic" diagnostics 0 type)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "一" "missing glyph text" diagnostics 0 text)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "12" "missing glyph source line" diagnostics 0 lines 0)

run_fontcollector(0 check "${A_ASS}")
require_contains("${FONTCOLLECTOR_STDOUT}" "OK: " "default human summary")

run_fontcollector(0 check "${A_ASS}" --details)
require_contains("${FONTCOLLECTOR_STDOUT}" "Parsing file" "detailed human events")
require_contains("${FONTCOLLECTOR_STDOUT}" "Font usage:" "detailed human usage")
require_contains("${FONTCOLLECTOR_STDOUT}" "names:" "detailed human font names")

run_fontcollector(0 list "${NESTED_TRANSFORM_ASS}" --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "missing" "nested transform font status" files 0 font_usage 0 matched_font match_status)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "DefinitelyMissingNestedFont" "nested transform font name" files 0 font_usage 0 ass_font facename)

run_fontcollector(0 check "${TAB_ASS}" --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "0" "literal tab missing glyph count" files 0 summary missing_glyph_font_count)

run_fontcollector(0 list "${SPACES_ASS}" --json)
json_length(space_codepoint_count "${FONTCOLLECTOR_STDOUT}" files 0 font_usage 0 codepoints values)
if(NOT space_codepoint_count EQUAL 4)
	message(FATAL_ERROR "expected A/B/C and one shared NBSP codepoint, got ${space_codepoint_count}\njson:\n${FONTCOLLECTOR_STDOUT}")
endif()
require_json_array_contains("${FONTCOLLECTOR_STDOUT}" "160" "literal NBSP and \\h codepoint" files 0 font_usage 0 codepoints values)

run_fontcollector(0 list "${WRAP_RESET_ASS}" --json)
json_length(wrap_reset_codepoint_count "${FONTCOLLECTOR_STDOUT}" files 0 font_usage 0 codepoints values)
if(NOT wrap_reset_codepoint_count EQUAL 4)
	message(FATAL_ERROR "expected omitted \\q to restore WrapStyle and collect a space, got ${wrap_reset_codepoint_count}\njson:\n${FONTCOLLECTOR_STDOUT}")
endif()
require_json_array_contains("${FONTCOLLECTOR_STDOUT}" "32" "omitted \\q restores WrapStyle" files 0 font_usage 0 codepoints values)

run_fontcollector(0 list "${ESCAPED_BRACES_ASS}" --json)
json_length(escaped_codepoint_count "${FONTCOLLECTOR_STDOUT}" files 0 font_usage 0 codepoints values)
if(NOT escaped_codepoint_count EQUAL 5)
	message(FATAL_ERROR "expected escaped braces without a backslash glyph, got ${escaped_codepoint_count}\njson:\n${FONTCOLLECTOR_STDOUT}")
endif()

run_fontcollector(0 list "${DRAWING_ASS}" --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "0" "pure drawing font usage" files 0 summary font_usage_count)

run_fontcollector(0 list "${NESTED_DRAWING_ASS}" --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "0" "nested pure drawing font usage" files 0 summary font_usage_count)

run_fontcollector(0 list "${NESTED_TEXT_ASS}" --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "1" "nested drawing reset font usage" files 0 summary font_usage_count)

run_fontcollector(0 list "${VARIANT_STATE_ASS}" --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "600" "variant effective weight" files 0 font_usage 0 ass_font effective_weight)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "600" "variant raw bold" files 0 font_usage 0 ass_font raw_bold_tag)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "1" "variant charset" files 0 font_usage 0 ass_font charset)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "-1" "variant raw charset" files 0 font_usage 0 ass_font raw_charset_tag)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "400" "variant event baseline weight" files 0 font_usage 0 ass_font baseline weight)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "600" "variant backend request" files 0 font_usage 0 matched_font backend_requested_weight)
require_not_contains("${FONTCOLLECTOR_STDOUT}" "\"realized_role\"" "unknown realized role is omitted")

run_fontcollector(0 check "${A_ASS}" --matcher libass --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "libass" "explicit libass matcher" matcher)
if(WIN32)
	require_json_equals("${FONTCOLLECTOR_STDOUT}" "directwrite" "libass matcher provider" provider)
else()
	require_json_equals("${FONTCOLLECTOR_STDOUT}" "fontconfig" "libass matcher provider" provider)
endif()
require_json_equals("${FONTCOLLECTOR_STDOUT}" "0" "libass matcher clean file" files 0 summary missing_glyph_font_count)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "lower_is_better" "libass score direction" files 0 font_usage 0 matched_font match_analysis score_order)
json_length(libass_candidate_count "${FONTCOLLECTOR_STDOUT}" files 0 font_usage 0 matched_font match_analysis candidates)
if(libass_candidate_count LESS 1)
	message(FATAL_ERROR "expected libass matcher candidate evidence\njson:\n${FONTCOLLECTOR_STDOUT}")
endif()

# Empty private catalog must fail closed (CLI + API).
run_fontcollector(1 check "${A_ASS}" --matcher libass --exclude-system-fonts)
require_contains("${FONTCOLLECTOR_STDERR}${FONTCOLLECTOR_STDOUT}" "exclude-system-fonts" "empty private catalog rejected")

# Unknown family under libass falls through to the configured default and then
# the provider fallback. DirectWrite does not substitute Aegisub's literal "Sans".
run_fontcollector(0 check "${MISSING_ASS}" --matcher libass --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "libass" "libass missing-font matcher" matcher)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "0" "libass default-family path not a hard miss" files 0 summary missing_font_count)
if(WIN32)
	require_json_equals("${FONTCOLLECTOR_STDOUT}" "fallback" "libass uses DirectWrite fallback for unknown name" files 0 font_usage 0 matched_font match_analysis candidates 0 match_source)
endif()

# Private-only fallback must select from the private catalog, not a system family.
if(WIN32 AND EXISTS "$ENV{WINDIR}/Fonts/arial.ttf")
	run_fontcollector(0 check "${MISSING_ASS}" --matcher libass
	                  --additional-fonts "$ENV{WINDIR}/Fonts/arial.ttf"
	                  --exclude-system-fonts --json)
	require_json_equals("${FONTCOLLECTOR_STDOUT}" "0" "private fallback finds an additional font" files 0 summary missing_font_count)
	require_json_equals("${FONTCOLLECTOR_STDOUT}" "fallback" "private catalog fallback source" files 0 font_usage 0 matched_font match_analysis candidates 0 match_source)
endif()

run_fontcollector(0 list "${A_ASS}" "${MISSING_ASS}")
require_contains("${FONTCOLLECTOR_STDOUT}" "Arial <Arial>" "list installed font")
require_contains("${FONTCOLLECTOR_STDOUT}" "DefinitelyMissingAegisubFont" "list missing font")
require_not_contains("${FONTCOLLECTOR_STDOUT}" "not installed" "old list missing suffix")

if(WIN32 AND EXISTS "$ENV{WINDIR}/Fonts/simhei.ttf")
	run_fontcollector(0 normalize "${SIMHEI_ASS}" --target localized --json)
	require_json_equals("${FONTCOLLECTOR_STDOUT}" "1" "localized normalize safe change count" summary safe_change_count)
	require_json_equals("${FONTCOLLECTOR_STDOUT}" "黑体" "localized normalize recommendation" files 0 changes 0 recommended_name)

	run_fontcollector(0 normalize "${SIMHEI_LOCALIZED_ASS}" --target english --json)
	require_json_equals("${FONTCOLLECTOR_STDOUT}" "2" "English normalize safe change count" summary safe_change_count)
	require_json_equals("${FONTCOLLECTOR_STDOUT}" "SimHei" "English normalize style recommendation" files 0 changes 0 recommended_name)
	require_json_equals("${FONTCOLLECTOR_STDOUT}" "SimHei" "English normalize override recommendation" files 0 changes 1 recommended_name)
	require_json_equals("${FONTCOLLECTOR_STDOUT}" "11" "English normalize override line" files 0 changes 1 source line)

	run_fontcollector(0 list "${SIMHEI_ASS}")
	require_contains("${FONTCOLLECTOR_STDOUT}" "黑体 <SimHei>" "list localized display font")

	run_fontcollector(0 list "${SIMHEI_ASS}" --json)
	require_json_equals("${FONTCOLLECTOR_STDOUT}" "黑体" "list json display font" files 0 font_usage 0 matched_font display_name)
	require_json_array_contains("${FONTCOLLECTOR_STDOUT}" "黑体" "list json localized font name" files 0 font_usage 0 matched_font names)
	require_json_array_contains("${FONTCOLLECTOR_STDOUT}" "SimHei" "list json English font name" files 0 font_usage 0 matched_font names)
endif()

run_fontcollector(0 list "${B_ASS}" --details)
require_contains("${FONTCOLLECTOR_STDOUT}" "Arial" "list detailed font")
require_contains("${FONTCOLLECTOR_STDOUT}" "matched: Arial" "list detailed matched font")
require_contains("${FONTCOLLECTOR_STDOUT}" "names:" "list detailed font names")
require_contains("${FONTCOLLECTOR_STDOUT}" "styles: Default" "list detailed styles")
require_contains("${FONTCOLLECTOR_STDERR}" "AssFontInfo 'Arial,0,0' Dialogue #12 is missing characters: 一" "list missing glyph diagnostic")

run_fontcollector(0 list "${MISSING_ASS}" --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "0" "list json result" result)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "missing" "list json match status" files 0 font_usage 0 matched_font match_status)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "DefinitelyMissingAegisubFont" "list json font name" files 0 font_usage 0 ass_font facename)

run_fontcollector(20 validate "${MISSING_ASS}" --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "20" "strict json result" result)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "0" "strict operation result" files 0 operation_result)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "missing_font" "missing font diagnostic" diagnostics 0 type)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "1" "missing font summary" summary missing_font_count)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "12" "missing font source line" diagnostics 0 lines 0)

run_fontcollector(6 check "${TEST_WORK_DIR}/does-not-exist.ass" "${A_ASS}" --json)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "6" "failed item result" files 0 result)
require_json_equals("${FONTCOLLECTOR_STDOUT}" "0" "successful item result" files 1 result)

run_fontcollector(0 collect "${A_ASS}" "${B_ASS}" --to "${COPY_DIR}")
if(NOT EXISTS "${COPY_DIR}/arial.ttf")
	message(FATAL_ERROR "expected collect to copy ${COPY_DIR}/arial.ttf")
endif()
