#include "../../src/ass_dialogue.h"
#include "../../src/ass_file.h"
#include "../../src/ass_parse_error.h"
#include "../../src/ass_parser.h"

#include <gtest/gtest.h>

TEST(ass_project_garbage, parses_secondary_subtitles_file) {
	AssFile file;
	AssParser parser(&file, 1);

	parser.AddLine("[Aegisub Project Garbage]");
	parser.AddLine("Secondary Subtitles File: ../secondary.ass");

	EXPECT_EQ("../secondary.ass", file.Properties.secondary_subtitles_file);
}

TEST(ass_parser, accepts_section_headers_with_surrounding_whitespace) {
	AssFile file;
	AssParser parser(&file, 1);

	parser.AddLine("  [Events]  ");
	parser.AddLine("Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,ok");

	ASSERT_EQ(1u, file.Events.size());
	EXPECT_EQ("ok", file.Events.front().Text.get());
}

TEST(ass_parser, accepts_script_type_with_compatible_suffix) {
	AssFile file;
	AssParser parser(&file, 0);

	parser.AddLine("[Script Info]");
	parser.AddLine("ScriptType: generated by tool v4.00+");
	parser.AddLine("[Events]");
	parser.AddLine("Dialogue: 9,0:00:00.00,0:00:01.00,Default,,0,0,0,,ass");

	ASSERT_EQ(1u, file.Events.size());
	EXPECT_EQ(9, file.Events.front().Layer);
}

TEST(ass_parser, rejects_v4pp_script_type) {
	AssFile file;
	AssParser parser(&file, 1);

	parser.AddLine("[Script Info]");
	EXPECT_THROW(parser.AddLine("ScriptType: v4.00++"), SubtitleFormatParseError);
}
