#include <gtest/gtest.h>

#include "../../src/ass_compat.h"
#include "../../src/ass_dialogue.h"
#include "../../src/ass_file.h"
#include "../../src/ass_info.h"
#include "../../src/ass_io_core.h"
#include "../../src/ass_style.h"

#include <libaegisub/vfr.h>

#include <filesystem>
#include <fstream>
#include <iterator>
#include <limits>
#include <map>

TEST(ass_file_extradata, cleaning_copy_does_not_mutate_original_file_state) {
	AssFile original;

	auto duplicate_a = original.AddExtradata("Key", "Value A");
	auto duplicate_b = original.AddExtradata("Key", "Value B");
	original.AddExtradata("Unused", "Orphaned");

	auto line = new AssDialogue;
	line->ExtradataIds = std::vector<uint32_t>{duplicate_a, duplicate_b};
	original.Events.push_back(*line);

	AssFile copy(original);
	copy.CleanExtradata();

	ASSERT_EQ(3u, original.Extradata.size());
	ASSERT_EQ(2u, original.Events.front().ExtradataIds.get().size());

	EXPECT_EQ(1u, copy.Extradata.size());
	EXPECT_EQ(1u, copy.Events.front().ExtradataIds.get().size());
}

TEST(ass_file_style_lookup, matches_renderer_compatible_default_and_starred_names) {
	AssFile file;
	file.Styles.push_back(*new AssStyle("Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,20,30,1"));
	file.Styles.push_back(*new AssStyle("Style: *Starred,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,20,30,1"));

	EXPECT_EQ("Default", file.GetStyle("*default")->name);
	EXPECT_EQ("*Starred", file.GetStyle("Starred")->name);
	EXPECT_EQ("*Starred", file.GetStyle("**Starred")->name);
}

TEST(ass_file_style_lookup, keeps_non_default_style_names_case_sensitive) {
	AssFile file;
	file.Styles.push_back(*new AssStyle("Style: Foo,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,20,30,1"));
	file.Styles.push_back(*new AssStyle("Style: foo,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,20,30,1"));

	EXPECT_EQ("Foo", file.GetStyle("Foo")->name);
	EXPECT_EQ("foo", file.GetStyle("foo")->name);
	EXPECT_EQ(nullptr, file.GetStyle("FOO"));
}

TEST(ass_file_style_lookup, shared_style_map_lookup_matches_renderer_compatible_names) {
	std::map<std::string, int> styles;
	styles["Default"] = 1;
	styles["*Starred"] = 2;
	styles["Foo"] = 3;

	EXPECT_EQ(1, AssCompat::FindStyle(styles, "*default")->second);
	EXPECT_EQ(2, AssCompat::FindStyle(styles, "Starred")->second);
	EXPECT_EQ(styles.end(), AssCompat::FindStyle(styles, "foo"));
}

TEST(ass_file_style_lookup, analyzes_renderer_compatibility_repairs_without_rewriting_on_read) {
	auto starred = AssCompat::AnalyzeStyleName("*Starred");
	EXPECT_TRUE(starred.has_compatibility_prefix);
	EXPECT_FALSE(starred.has_default_case_mismatch);
	EXPECT_TRUE(starred.NeedsExplicitRepair());
	EXPECT_EQ("Starred", starred.suggested_name);

	auto default_case = AssCompat::AnalyzeStyleName("*default");
	EXPECT_TRUE(default_case.has_compatibility_prefix);
	EXPECT_TRUE(default_case.has_default_case_mismatch);
	EXPECT_TRUE(default_case.NeedsExplicitRepair());
	EXPECT_EQ("Default", default_case.suggested_name);

	auto ordinary = AssCompat::AnalyzeStyleName("foo");
	EXPECT_FALSE(ordinary.has_compatibility_prefix);
	EXPECT_FALSE(ordinary.has_default_case_mismatch);
	EXPECT_FALSE(ordinary.NeedsExplicitRepair());
	EXPECT_EQ("foo", ordinary.suggested_name);
}

TEST(ass_compat_format, formats_canonical_ass_values) {
	EXPECT_EQ("-12", AssCompat::FormatInteger(-12));
	EXPECT_EQ("4294967295", AssCompat::FormatUnsignedInteger(4294967295u));
	EXPECT_EQ("1.25", AssCompat::FormatFloat(1.25));
	EXPECT_EQ("2", AssCompat::FormatFloat(2.0));
	EXPECT_EQ("0", AssCompat::FormatFloat(0.0));
	EXPECT_EQ("0", AssCompat::FormatFloat(-0.0));
	EXPECT_EQ("0", AssCompat::FormatFloat(-0.0004));
	EXPECT_EQ("0", AssCompat::FormatFloat(std::numeric_limits<double>::infinity()));
	EXPECT_EQ("0", AssCompat::FormatFloat(std::numeric_limits<double>::quiet_NaN()));
	EXPECT_EQ("0:00:12.34", AssCompat::FormatTime(12345));
	EXPECT_EQ("12:00:00.005", AssCompat::FormatTime(43200005, true));
	EXPECT_EQ("&H04030201", AssCompat::FormatStyleColor(agi::Color(1, 2, 3, 4)));
	EXPECT_EQ("&H030201&", AssCompat::FormatOverrideColor(agi::Color(1, 2, 3, 4)));
	EXPECT_EQ("&HFF&", AssCompat::FormatOverrideAlpha(300));
}

TEST(ass_compat_parse, rejects_non_finite_floats) {
	double value = 1.0;

	EXPECT_FALSE(AssCompat::ParseFloat("nan", value));
	EXPECT_FALSE(AssCompat::ParseFloat("inf", value));
	EXPECT_EQ(1.0, value);
}

TEST(ass_io_core, ass_writer_canonicalizes_script_type) {
	AssFile file;
	file.Info.emplace_back("Title", "ScriptType test");
	file.Info.emplace_back("ScriptType", "generated by tool v4.00+");

	auto path = std::filesystem::temp_directory_path() / "aegisub-script-type-canonical.ass";
	WriteAssFileForCore(&file, path, agi::vfr::Framerate(), "UTF-8", AssWriteOptions{});

	std::string text;
	{
		std::ifstream input(path, std::ios::binary);
		text.assign(std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>());
	}
	std::filesystem::remove(path);

	EXPECT_NE(std::string::npos, text.find("ScriptType: v4.00+"));
	EXPECT_EQ(std::string::npos, text.find("generated by tool"));
}

TEST(ass_io_core, ass_writer_uses_legacy_rounding_instead_of_frame_safe_projection) {
	AssFile file;
	file.Info.emplace_back("ScriptType", "v4.00+");
	AssStyle style;
	file.Styles.push_back(style);

	AssDialogue line;
	line.Start = 18;
	line.End = 19;
	line.Style = "Default";
	line.Text = "short";
	file.Events.push_back(line);

	auto path = std::filesystem::temp_directory_path() / "aegisub-ass-writer-legacy-time.ass";
	WriteAssFileForCore(&file, path, agi::vfr::Framerate(100.0), "UTF-8", AssWriteOptions{});

	std::string text;
	{
		std::ifstream input(path, std::ios::binary);
		text.assign(std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>());
	}
	std::filesystem::remove(path);

	EXPECT_NE(std::string::npos, text.find("Dialogue: 0,0:00:00.02,0:00:00.02,Default,,0,0,0,,short"));
	EXPECT_EQ(std::string::npos, text.find("Dialogue: 0,0:00:00.01,0:00:00.02,Default,,0,0,0,,short"));
}
