// Copyright (c) 2014, Thomas Goyne <plorkyeran@aegisub.org>
// Copyright (c) 2026, MIR
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//
// Aegisub Project http://www.aegisub.org/

#include "subtitle_format_ass.h"

#include "ass_file.h"
#include "ass_io_core.h"
#include "options.h"
#include "version.h"

namespace {
std::string AegisubGeneratorHeader() {
	return std::string("; Script generated by Aegisub ")
		+ GetAegisubLongVersionString()
		+ AssStorageLineBreak()
		+ "; http://www.aegisub.org/"
		+ AssStorageLineBreak();
}

bool GetConfiguredSaveUiState() {
	return config::GetBoolOptionOrDefault("App/Save UI State", true);
}
}

void AssSubtitleFormat::ReadFile(AssFile *target, agi::fs::path const& filename, agi::vfr::Framerate const& fps, std::string const& encoding, std::shared_ptr<agi::SingleChoiceInteractionSink> choice_sink, std::shared_ptr<agi::BackgroundRunnerFactory>) const {
	(void)choice_sink;
	(void)fps;
	ReadAssFileForCore(target, filename, encoding);
}

void AssSubtitleFormat::WriteFile(const AssFile *src, agi::fs::path const& filename, agi::vfr::Framerate const& fps, std::string const& encoding, std::shared_ptr<agi::SingleChoiceInteractionSink> choice_sink) const {
	(void)choice_sink;
	AssWriteOptions options;
	options.write_generator = true;
	options.generator_header = AegisubGeneratorHeader();
	options.write_project_garbage = true;
	options.write_ui_state = GetConfiguredSaveUiState();
	options.write_extradata = true;
	WriteAssFileForCore(src, filename, fps, ResolveWriteEncoding(encoding), options);
}

void AssSubtitleFormat::ExportFile(const AssFile *src, agi::fs::path const& filename, agi::vfr::Framerate const& fps, std::string const& encoding, std::shared_ptr<agi::SingleChoiceInteractionSink> choice_sink) const {
	(void)choice_sink;
	AssWriteOptions options;
	options.write_generator = true;
	options.generator_header = AegisubGeneratorHeader();
	WriteAssFileForCore(src, filename, fps, ResolveWriteEncoding(encoding), options);
}
