find_package(PkgConfig QUIET)
pkg_check_modules(PC_FFMS2 QUIET ffms2)
if(DEFINED FFMS2_INCLUDE_DIR AND NOT IS_ABSOLUTE "${FFMS2_INCLUDE_DIR}")
  get_filename_component(FFMS2_INCLUDE_DIR "${FFMS2_INCLUDE_DIR}" ABSOLUTE BASE_DIR "${CMAKE_SOURCE_DIR}")
endif()
if(FFMS2_INCLUDE_DIR
  AND NOT EXISTS "${FFMS2_INCLUDE_DIR}/ffms.h"
  AND NOT EXISTS "${FFMS2_INCLUDE_DIR}/ffmscompat.h")
  unset(FFMS2_INCLUDE_DIR CACHE)
  unset(FFMS2_INCLUDE_DIR)
endif()
find_path(FFMS2_INCLUDE_DIR
  NAMES ffms.h ffmscompat.h
  HINTS ${FFMS2_INCLUDE_DIR}
  HINTS ${PC_FFMS2_INCLUDE_DIRS}
)
set(FFMS2_VERSION ${PC_FFMS2_VERSION})
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(FFMS2
  FOUND_VAR FFMS2_FOUND
  REQUIRED_VARS
    FFMS2_INCLUDE_DIR
  VERSION_VAR FFMS2_VERSION
)
