// Copyright (c) 2026, MIRIMIRIM

#pragma once

#include <stddef.h>

#if defined(_WIN32)
#if defined(AEGISUB_FONTCOLLECTOR_BUILD)
#define AEGISUB_FONTCOLLECTOR_API __declspec(dllexport)
#else
#define AEGISUB_FONTCOLLECTOR_API __declspec(dllimport)
#endif
#else
#define AEGISUB_FONTCOLLECTOR_API __attribute__((visibility("default")))
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef enum AegisubFontCollectorMode {
	AEGISUB_FONTCOLLECTOR_MODE_CHECK = 0,
	AEGISUB_FONTCOLLECTOR_MODE_COPY_TO_FOLDER = 1,
	AEGISUB_FONTCOLLECTOR_MODE_COPY_TO_SCRIPT_FOLDER = 2,
	AEGISUB_FONTCOLLECTOR_MODE_COPY_TO_ZIP = 3,
	AEGISUB_FONTCOLLECTOR_MODE_SYMLINK_TO_FOLDER = 4
} AegisubFontCollectorMode;

typedef enum AegisubFontCollectorResult {
	AEGISUB_FONTCOLLECTOR_OK = 0,
	AEGISUB_FONTCOLLECTOR_INVALID_ARGUMENT = 1,
	AEGISUB_FONTCOLLECTOR_INVALID_MODE = 2,
	AEGISUB_FONTCOLLECTOR_INVALID_DESTINATION = 3,
	AEGISUB_FONTCOLLECTOR_UNSUPPORTED_MODE = 4,
	AEGISUB_FONTCOLLECTOR_READ_FAILED = 5,
	AEGISUB_FONTCOLLECTOR_COLLECT_FAILED = 6
} AegisubFontCollectorResult;

typedef enum AegisubFontCollectorEventType {
	AEGISUB_FONTCOLLECTOR_EVENT_UPDATING_FONT_CACHE,
	AEGISUB_FONTCOLLECTOR_EVENT_FONT_CACHE_ERROR,
	AEGISUB_FONTCOLLECTOR_EVENT_PARSING_FILE,
	AEGISUB_FONTCOLLECTOR_EVENT_STYLE_MISSING,
	AEGISUB_FONTCOLLECTOR_EVENT_SEARCHING_FOR_FONT_FILES,
	AEGISUB_FONTCOLLECTOR_EVENT_FONT_MISSING,
	AEGISUB_FONTCOLLECTOR_EVENT_FONT_FOUND,
	AEGISUB_FONTCOLLECTOR_EVENT_FAKE_BOLD,
	AEGISUB_FONTCOLLECTOR_EVENT_FAKE_ITALIC,
	AEGISUB_FONTCOLLECTOR_EVENT_MISSING_GLYPHS,
	AEGISUB_FONTCOLLECTOR_EVENT_USAGE,
	AEGISUB_FONTCOLLECTOR_EVENT_SEARCH_COMPLETE,
	AEGISUB_FONTCOLLECTOR_EVENT_ALL_FONTS_FOUND,
	AEGISUB_FONTCOLLECTOR_EVENT_FONTS_MISSING,
	AEGISUB_FONTCOLLECTOR_EVENT_FONTS_MISSING_GLYPHS,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_SYMLINKING_FONTS_TO_FOLDER,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_COPYING_FONTS_TO_FOLDER,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_COPYING_FONTS_TO_ARCHIVE,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_FAILED_CREATE_DIRECTORY,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_FAILED_OPEN,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_COPIED,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_ALREADY_EXISTS,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_SYMLINKED,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_FAILED_COPY,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_DONE_ALL_COPIED,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_DONE_SOME_NOT_COPIED,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_OVER_32MB_WARNING,
	AEGISUB_FONTCOLLECTOR_EVENT_COLLECTION_NEWLINE
} AegisubFontCollectorEventType;

typedef struct AegisubFontCollectorRequest {
	/* Paths and encoding names are UTF-8 strings. */
	char const *input_path;
	char const *destination_path;
	char const *encoding;
	AegisubFontCollectorMode mode;
} AegisubFontCollectorRequest;

typedef struct AegisubFontCollectorEvent {
	AegisubFontCollectorEventType type;
	char const *face;
	char const *message;
	char const *style;
	char const *path;
	char const *const *styles;
	size_t style_count;
	int const *lines;
	size_t line_count;
	int count;
} AegisubFontCollectorEvent;

/* Event pointer fields are valid only for the duration of the callback. */
typedef void (*AegisubFontCollectorEventCallback)(AegisubFontCollectorEvent const *event, void *user_data);

AEGISUB_FONTCOLLECTOR_API int aegisub_fontcollector_collect(
	AegisubFontCollectorRequest const *request,
	AegisubFontCollectorEventCallback callback,
	void *user_data,
	char *error_buffer,
	size_t error_buffer_size);

#ifdef __cplusplus
}
#endif
